from tensorflow.keras.models import load_model  # pyright: ignore[reportMissingImports]
import joblib
import numpy as np
model_white=joblib.load("white_model.keras")
scaler=joblib.load("scaler_white.pkl")
fa=float(input("Enter fixed acidity:"))
va=float(input("Enter volatile acidity:"))
ca=float(input("Enter citric acid:"))
rs=float(input("Enter residual sugar:"))
ch=float(input("Enter chlorides:"))
fsd=float(input("Enter free sulfur dioxide:"))
tsd=float(input("Enter total sulfur dioxide:"))
d=float(input("Enter density:"))
ph=float(input("Enter pH:"))
s=float(input("Enter sulphates:"))
a=float(input("Enter alcohol:"))
input_data=np.array([[fa,va,ca,rs,ch,fsd,tsd,d,ph,s,a]])
scaled_data=scaler.transform(input_data)
Predicted_quality=model_white.predict(scaled_data)
print("Predicted Quality:",Predicted_quality[0][0])
Rounded_Quality=round(Predicted_quality[0][0])
print("Rounded Quality:",Rounded_Quality)
Accurate_quality=int(Predicted_quality[0][0])
print("Accurate_Quality:",Accurate_quality)